server:
  port: 8888

spring:
  cloud:
    config:
      label: main,master,desarrollo,repoGitStatic
      enabled: true
      server:
        git:
          uri: C:\Users\jgalvez\Developer\proyectos\SCloudConfig\repositoryGit

